version = 1

[[analyzers]]
name = "solhint"
type = "community"

[[analyzers]]
name = "slither"
type = "community"

[[analyzers]]
name = "kube-linter"
type = "community"

[[analyzers]]
name = "dart-analyze"
type = "community"

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[analyzers]]
name = "cfn-lint"
type = "community"